
-- Explore total_rate field ,Show meal cost 

EVALUATE
	SELECTCOLUMNS(
		Reservations,
		Reservations[adults],
		Reservations[children],
		Reservations[avg_daily_rate],
		Reservations[total_stay_nights],
		Reservations[meal_cost],
		Reservations[total_rate])
	

	
-- Explore marketing segment discounts over total
EVALUATE
	SELECTCOLUMNS(
		Reservations,
		Reservations[market_segment],
		RELATED(MarketSegment[Discount]),
		Reservations[avg_daily_rate],
		Reservations[total_stay_nights],
		Reservations[accomodation_rate],
		Reservations[total_rate]
	)
	
------------------------------------------
-- Agents
------------------------------------------


-- How many agents work with us?
EVALUATE
	{COUNTX(DISTINCT(Reservations[agent]), [agent])}
	
-- How are reservations distributed by agent?
EVALUATE
	SUMMARIZECOLUMNS(
		Reservations[agent],
		FILTER(Reservations, NOT ISBLANK(Reservations[agent])),
		"Booking Volume", [Total Reservations],
		"% of Total", ROUND(
						DIVIDE(
							[Total Reservations],
							CALCULATE([Total Reservations], ALL(), NOT ISBLANK(Reservations[agent]))) * 100,
							3
						),
		"Produced Income", IF(ISBLANK([Income]), 0, [Income]),
		"Booking Effectiveness %", ROUND(
						DIVIDE([Total Reservations] - [Cancelled Reservations],
								[Total Reservations]) * 100,
							2
						),
		"Earned Comissions", [Agent Comissions]
	)
	
// Just getting random sample to verify agent_comission calculation
EVALUATE
	SAMPLE(10, 
			SELECTCOLUMNS(Reservations,
				Reservations[is_canceled],
				Reservations[reservation_status],
				Reservations[agent],
				Reservations[accomodation_rate],
				Reservations[agent_comission]),
			RAND()
		)