
-- Explore total_rate field ,Show meal cost 

EVALUATE
	SELECTCOLUMNS(
		Reservations,
		Reservations[adults],
		Reservations[children],
		Reservations[avg_daily_rate],
		Reservations[total_stay_nights],
		Reservations[meal_cost],
		Reservations[total_rate])
	

EVALUATE
	ALL(Reservations[meal])
	
-- Explore marketing segment discounts over total
EVALUATE
	SELECTCOLUMNS(
		Reservations,
		Reservations[market_segment],
		RELATED(MarketSegment[Discount]),
		Reservations[total_rate]
	)
	
EVALUATE
	{CALCULATE(COUNT(Reservations[market_segment]), Reservations[market_segment] = "Offline TA")}
	
------------------------------------------
-- Agents
------------------------------------------


-- How many agents work with us?
EVALUATE
	{COUNTX(DISTINCT(Reservations[agent]), [agent])}
	
-- How are reservations distributed by agent?
EVALUATE
	SUMMARIZECOLUMNS(
		Reservations[agent],
		FILTER(Reservations, NOT ISBLANK(Reservations[agent])),
		"Booking Volume", [Total Reservations],
		"% of Total", ROUND(
						DIVIDE(
							[Total Reservations],
							CALCULATE([Total Reservations], ALL(), NOT ISBLANK(Reservations[agent]))) * 100,
							3
						),
		"Produced Income", [Income]
	)