
-- Explore total_rate field ,Show meal cost 

EVALUATE
	SELECTCOLUMNS(
		Reservations,
		Reservations[adults],
		Reservations[children],
		Reservations[avg_daily_rate],
		Reservations[total_stay_nights],
		Reservations[meal_cost],
		Reservations[total_rate])
	

	
-- Explore marketing segment discounts over total
EVALUATE
	SELECTCOLUMNS(
		Reservations,
		Reservations[market_segment],
		RELATED(MarketSegment[Discount]),
		Reservations[avg_daily_rate],
		Reservations[total_stay_nights],
		Reservations[accomodation_rate],
		Reservations[total_rate]
	)
	
------------------------------------------
-- Agents
------------------------------------------


-- How many agents work with us?
EVALUATE
	{COUNTX(DISTINCT(Reservations[agent]), [agent])}
	
-- How are reservations distributed by agent?
EVALUATE
	SUMMARIZECOLUMNS(
		Reservations[agent],
		FILTER(Reservations, NOT ISBLANK(Reservations[agent])),
		"Produced Income", ROUND(IF(ISBLANK([Income]), 0, [Income]), 2),
		"Income %", [Income %],
		"Booking Effectiveness %", ROUND([Booking Effectivenes %] * 100, 2),
		"Booking Volume", [Total Reservations],
		"Volume %", ROUND([Booking Volume %], 3),
		"Earned Comissions", ROUND([Agent Comissions], 2)
	)
	
// Just getting random sample to verify agent_comission calculation
EVALUATE
	SAMPLE(10, 
			SELECTCOLUMNS(Reservations,
				Reservations[is_canceled],
				Reservations[reservation_status],
				Reservations[agent],
				Reservations[accomodation_rate],
				Reservations[agent_comission]),
			RAND()
		)
		
EVALUATE
	// Ranking is based on following criteria:
	// 1. Produced Income % - 80% weight
	// 2. Booking Effectiveness % - 15% weight
	// 3. Booking Volume % - 5% weight

	VAR AgentsRanking = 
		ADDCOLUMNS(
			VALUES(Reservations[agent]),
			"Income%", ROUND([Income %] * 100, 2),
			"Effectiveness%", ROUND([Booking Effectivenes %] * 100, 2),
			"Volume%", ROUND([Booking Volume %] * 100, 2)
		)
		
	RETURN ADDCOLUMNS(
		AgentsRanking,
		"Rank", RANKX(AgentsRanking, [Income%] * 0.80 + [Effectiveness%] * 0.15 + [Volume%] * 0.05)
	)
	
	ORDER BY [Rank]
	